language: node_js

node_js:
- 'lts/*'
- 'stable'

cache: npm

before_install:
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_USER"
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - git clone "https://$GH_USER:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git" $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_BRANCH
  - npm i -g makeshift && makeshift -r registry.npmjs.org

script: echo "Running tests against $(node -v) ..."

before_deploy:
  - chmod +x scripts/semver.sh
  - chmod +x scripts/bump-version.sh
  - git update-index --assume-unchanged scripts/bump-version.sh
  - git update-index --assume-unchanged scripts/semver.sh

# Deployment stage that only runs for the latest 
jobs:
  include:
    - stage: deploy
      name: "Publish a new distribution to NPM"
      node_js: 'stable'
      script: scripts/bump-version.sh $TRAVIS_BRANCH $TRAVIS_EVENT_TYPE
      skip_cleanup: true
      if: fork = false AND type = push AND repo = romcal/romcal 

after_deploy:
  - git update-index --no-assume-unchanged scripts/bump-version.sh
  - git update-index --no-assume-unchanged scripts/semver.sh

notifications:
  email:
    recipients:
    - $GH_EMAIL
    on_success: change
    on_failure: always

env:
  global:
  - secure: AiE2x1JZkOF7Y6fS8Up4HGP8/bRpLxBe/lRgLBJAVbYYatJgNrUHZtMjTG+7kg3IhZ5GqBLwBrxBr+m4kSiIMwusnb7JEBq+w/eR+URx7Ts54cTeLGouyzmr4eSBcsOlHilf2R9z14zhSPjn/eRMyYFBkMTUvr7qSXfVzKrIre0=
  - secure: VFUnEUOK+B3DQqIkR2Uinmm5j5QO6iSI8FPhKGgb1t3jR0KUDfkl/ZIilQ79nroLIo6pQYIldw1en7mhYHDkm0V+d/10fifqW2/7b0tmqMO30xkpFOabasX2p741kpoHfqPDAqR+XhwFhFVSI0uSuyVEtyrYGHDceQOiV9aDp9k=
  - secure: A8RCEeCTUoinBOhbjGKMjWlGVyQL3/6jfEjS8PUcorE+bL8//upg+mM1X1O0l23D/PiralARpsbAsfYDf3Z0CBBWe9AnM/4/lUZO7xav5Y8IxnMgRsJ402ATHRMXpupf3pxNFpzH7hdkjFta6nZTh8zb9aQfpxSLlAdHPqD8aFc=
  - secure: X/5sWzfiUJu/629Aeuasl7Ip7sH+eD+3d2gizfDO/EtHnjGxLMT3LcIqMNCSV7mvLPbFMxLwFMTz27JNFJCCCZHVCgtr0RFxw76GAn4LeLygGH9R+GyR8iC1NST5Qa9COkgIZUeFHUhfqkyiklzF+GD1DSn51mJZ1TR3iloaEss=
