language: node_js
node_js:
  - "13"

cache:
  directories:
    - "node_modules"

# Create a temporary .npmrc file to be used for deployments
before_install:
  - npm i -g makeshift && makeshift -r registry.npmjs.org

# Custom build phase
# script:
#  - npm run test

# Temporarily skip tests
script: 'true'

before_deploy:
  - npm run-script build

# Custom deployment script
deploy:
  - provider: script
    script: chmod +x scripts/bump-version.sh && scripts/bump-version.sh $RAVIS_BRANCH $TRAVIS_EVENT_TYPE
    on:
      all_branches: true

  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true

# notify owners
notifications:
  email:
    recipients:
      - bleushade@gmail.com
    on_success: change
    on_failure: always
